### ISSUE TITLE
{"addresses": "$[] address"} is not supported  ？

### ISSUE THREAD

**Issue by nooto** [appnormal/apn_json2model#1]
i  have define  list  in  WaybillListResp.json 
{
  "list": "$[]WaybillDetailResp"
}

`want  List<WaybillDetailResp>    but  get    List<Map>
`
```
  factory WaybillListResp.fromJson(Map<String,dynamic> json) => WaybillListResp(
    list: json['list'] as List<WaybillDetailResp>   ~~~~~?????????
  );

```

**Comment by nooto** [comment]
> WaybillListResp

see   json_to_model   there is  a file   WaybillListResp.g.dart  ware create to parse jsonToModel.

apn_jsong2model don't need this file？


Please provide an example project？

**Comment by mark-nicepants** [comment]
Hey Nooto, 

apn_json2model does not generated .g.dart files. Just normal models.

Given your example you should also have a separate json named `waybill_detail_resp.json`.

Within that json you can put the definition of your detail model.

```json
{
"list": "$[]waybill_detail_resp"
}
```

Should work after that.

**Comment by nooto** [comment]
> Hey Nooto,
> 
> apn_json2model does not generated .g.dart files. Just normal models.
> 
> Given your example you should also have a separate json named `waybill_detail_resp.json`.
> 
> Within that json you can put the definition of your detail model.
> 
> ```json
> {
> "list": "$[]waybill_detail_resp"
> }
> ```
> 
> Should work after that.

yeah  IT WORK!!   thanks!!

**Comment by mark-nicepants** [comment]
Nice I updated the example with a case with 2 json files and a list 😄
