### ISSUE TITLE
subdirs?

### ISSUE THREAD

**Issue by etoiledemer** [appnormal/apn_json2model#2]
Hi,

Is it possible to put json files in subdirs?
 like this:
```
/jsons
   a/
       a.json
   b/
       b.json
```

it seems to break import paths in code generation and it seems impossible to nest models from other subdirs. If I nest a model from another subdir, the code in the `fromJson(...)` is not correct.

example if I import 
```
{"price":"$../product/price"}
```
, then the output in `fromJson()` is 
```
price: json['price'] as Price,
```
when in fact the content of `fromJson()` should be :
```
price: Price.fromJson(json['price'] as Map<String, dynamic>),
```
If you have hundreds of `.json` files, do you put them all directly under `/jsons/` ?

**Comment by etoiledemer** [comment]
quite fixed by https://github.com/fadhilx/json_to_model/pull/24 
please merge

**Comment by mark-nicepants** [comment]
You can switch back to json_to_model version 3.0.2 that will be release in a short while. This repo is entirely merged in the original package en therefor no longer needed.
